const  menus=[
  {
    id:1,
    is_active:true,
    icon:"fas fa-align-justify",
    name:"Button",
    href:"#/base/buttons",
    children:[],
  },

  {
    id:2,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"Button Group",
    children:[],
    href:"#/base/button_group",
  },
  {
    id:3,
    icon:"fas fa-align-justify",
    name:"Modal",
    badge:20000,
    children:[],
    href:"#/base/modal",
  },
  {
    id:4,
    icon:"fas fa-align-justify",
    name:"Alert",
    badge:"pro",
    children:[],
    href:"#/base/alert",
  },
  {
    id:5,
    icon:"fas fa-align-justify",
    name:"table",
     badge:"new",
    children:[],
  },
  {
    id:6,
    icon:"fas fa-align-justify",
    name:"component",
    badge:99,
    children:[],
  },
  {
    id:7,
    icon:"fas fa-align-justify",
    name:"pages",
    badge:6,
    children:[],
  },
  {
    id:8,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:9,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:10,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:11,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:12,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:13,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:14,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:15,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
  {
    id:16,
    is_active:false,
    icon:"fas fa-align-justify",
    name:"skin",
    children:[],
  },
]

export default menus